USE master
GO

--========== TẠO DATABASE  ==========--
CREATE DATABASE QUANLYDODUNGVANPHONG
GO




USE QUANLYDODUNGVANPHONG
GO

--========== TẠO BẢNG ==========--
CREATE TABLE THONGTINCANHAN
(
    CMND VARCHAR(20) NOT NULL,
    HOTEN NVARCHAR(50) NOT NULL,
    DIENTHOAI VARCHAR(20),
    DIACHI NVARCHAR(100),
    GIOITINH INT NOT NULL,
    NGAYSINH DATE,
    CONSTRAINT THONGTINCANHAN_CK_GIOITINH CHECK (GIOITINH IN (0, 1)),
    CONSTRAINT THONGTINCANHAN_PK PRIMARY KEY (CMND)
)
GO

CREATE TABLE KHACHHANG
(
    MAKH VARCHAR(10) NOT NULL,
    CMND VARCHAR(20) NOT NULL,
    NGAYHETHAN DATE,
    CONSTRAINT KHACHHANG_PK PRIMARY KEY (MAKH),
    CONSTRAINT KHACHHANG_FK_THONGTINCANHAN FOREIGN KEY (CMND) REFERENCES THONGTINCANHAN (CMND) ON DELETE CASCADE
)
GO

CREATE TABLE NHANVIEN
(
    MANV VARCHAR(10) NOT NULL,
    CMND VARCHAR(20) NOT NULL,
    MOTA NVARCHAR(100),
    CONSTRAINT NHANVIEN_PK PRIMARY KEY (MANV),
    CONSTRAINT NHANVIEN_FK_THONGTINCANHAN FOREIGN KEY (CMND) REFERENCES THONGTINCANHAN (CMND) ON DELETE CASCADE
)
GO

CREATE TABLE TAIKHOAN
(
    TENTAIKHOAN VARCHAR(30) NOT NULL,
    MATKHAU NVARCHAR(128) NOT NULL,
    LOAITK SMALLINT NOT NULL,
    MANV VARCHAR(10) NOT NULL,
    CONSTRAINT TAIKHOAN_PK PRIMARY KEY (TENTAIKHOAN),
    CONSTRAINT TAIKHOAN_FK_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV) ON DELETE CASCADE
)
GO

CREATE TABLE DODUNGVANPHONG
(
    MADD NVARCHAR(10) NOT NULL,
    TENDD NVARCHAR(50) NOT NULL,
    HANGSANXUAT NVARCHAR(50) NOT NULL,
    GHICHU NVARCHAR(100),
    DONGIA MONEY NOT NULL,
    TINHTRANG INT,
    THELOAI NVARCHAR(30) NOT NULL,
    SOLUONGTON INT NOT NULL,
    CONSTRAINT DODUNGVANPHONG_PK PRIMARY KEY (MADD),
    CONSTRAINT DODUNGVANPHONG_CK_TINHTRANG CHECK (TINHTRANG IN (0, 1))
)
GO

CREATE TABLE HOADON
(
    MAHD VARCHAR(10) NOT NULL,
    NGAYLAP DATE,
    MAKH VARCHAR(10) NOT NULL,
    CONSTRAINT HOADON_PK PRIMARY KEY (MAHD),
    CONSTRAINT HOADON_FK_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH)
)
GO

CREATE TABLE CHITIETHOADON
(
    MAHD VARCHAR(10) NOT NULL,
    MADD NVARCHAR(10) NOT NULL,
    SONGAYDUOCMUON INT NOT NULL,
    SOLUONG INT NOT NULL,
    TINHTRANG INT NOT NULL,
    CONSTRAINT CHITIETHOADON_PK PRIMARY KEY (MAHD),
    CONSTRAINT CHITIETHOADON_FK_DODUNGVANPHONG FOREIGN KEY (MADD) REFERENCES DODUNGVANPHONG (MADD),
    CONSTRAINT CHITIETHOADON_FK_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD) ON DELETE CASCADE
)
GO

-- add rule 
ALTER TABLE KHACHHANG
    -- lấy ngày hết hạn tính từ thời gian khởi tạo mặt hàng 
    ADD CONSTRAINT KHACHHANG_DF_NGAYHETHAN DEFAULT DATEADD(YEAR, 3, GETDATE()) FOR NGAYHETHAN
GO

ALTER TABLE DODUNGVANPHONG
    -- default tình trạng là mới khi khởi tạo
    ADD CONSTRAINT DODUNGVANPHONG_DF_TINHTRANG DEFAULT 1 FOR TINHTRANG
GO

ALTER TABLE HOADON
    ADD CONSTRAINT HOADON_DF_NGAYLAP DEFAULT GETDATE() FOR NGAYLAP
GO

--========== TRIGGER ==========--
CREATE TRIGGER TRG_THEMHOADON
    ON CHITIETHOADON
    AFTER INSERT AS
BEGIN
    UPDATE DODUNGVANPHONG
    SET SOLUONGTON = SOLUONGTON - (
        SELECT SOLUONG
    FROM inserted
    WHERE MADD = DD.MADD
    )
    FROM DODUNGVANPHONG DD
        JOIN inserted I
        ON DD.MADD = I.MADD
END
GO

CREATE TRIGGER TRG_CAPNHATHOADON
    ON CHITIETHOADON
    AFTER UPDATE AS
BEGIN
    UPDATE DODUNGVANPHONG
    SET SOLUONGTON = SOLUONGTON - (
        SELECT SOLUONG
        FROM inserted
        WHERE MADD = DD.MADD
        ) + (
            SELECT SOLUONG
            FROM deleted
            WHERE MADD = DD.MADD
            )
    FROM DODUNGVANPHONG DD
        JOIN deleted D
        ON DD.MADD = D.MADD
END
GO

CREATE TRIGGER TRG_XOAHOADON
    ON CHITIETHOADON
    FOR DELETE AS
BEGIN
    UPDATE DODUNGVANPHONG
    SET SOLUONGTON = SOLUONGTON + (
        SELECT SUM(SOLUONG)
        FROM deleted
        WHERE MADD = DD.MADD
        )
    FROM DODUNGVANPHONG DD
        JOIN deleted D
        ON DD.MADD = D.MADD
END
GO

--========== THÊM DỮ LIỆU ==========--
INSERT INTO THONGTINCANHAN
    (CMND, HOTEN, DIENTHOAI, DIACHI, GIOITINH, NGAYSINH)
VALUES
    ('111111111', N'Buffalo Coder', '0982505701', N'IUH', 1, '1999-02-24')
GO

INSERT INTO NHANVIEN
    (MANV, CMND, MOTA)
VALUES
    ('NV00001', '111111111', N'ADMIN')
GO

INSERT INTO TAIKHOAN
    (TENTAIKHOAN, MATKHAU, LOAITK, MANV)
VALUES
    ('admin', 'admin', 1, 'NV00001')
GO