-- use for quanglybangdia
USE master;
GO
ALTER DATABASE QUANLYBANGDIA 
SET SINGLE_USER 
WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE QUANLYBANGDIA


--  user for quanlydodungvanphong
USE master;
GO
ALTER DATABASE QUANLYDODUNGVANPHONG
SET SINGLE_USER 
WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE QUANLYDODUNGVANPHONG