/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import VTabbed.QuanLyChoThueTab;
import VTabbed.QuanLyKhachHangTab;
import VTabbed.QuanLyMatHangTab;
import VTabbed.QuanLyNhanVienTab;
import VTabbed.ThongKeTab;
import VTabbed.CaiDatTab;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author quang
 */
public class Admin extends JFrame {
   // private final boolean IS_ADMIN = DangNhap.taiKhoan.getLoaiTaiKhoan() == 1;
    private QuanLyKhachHangTab quanLyKhachHangTab;
    private QuanLyMatHangTab quanLyMatHangTab;
    private QuanLyChoThueTab quanLyChoThueTab;
    private QuanLyNhanVienTab quanLyNhanVienTab;
    private ThongKeTab thongKeTabbed;
    private CaiDatTab caiDatTabbed;
    private void prepareUI() throws Exception{
        //TabKhachHang = new JTabbedPane(JTabbedPane.LEFT);
        TabKhachHang.add("Quản lý mặt hàng",quanLyMatHangTab = new QuanLyMatHangTab());
        TabKhachHang.add("Quản lý khách hàng",quanLyKhachHangTab = new QuanLyKhachHangTab());
        TabKhachHang.add("Quản lý cho thuê",quanLyChoThueTab = new QuanLyChoThueTab());
        TabKhachHang.add("Quản lý nhân viên",quanLyNhanVienTab = new QuanLyNhanVienTab());
        TabKhachHang.add("Thống kê", thongKeTabbed = new ThongKeTab());
        TabKhachHang.add("Cài đặt", caiDatTabbed = new CaiDatTab());
        TabKhachHang.addChangeListener(menuTabbed_Change());
    }
    
    /**
     * Sự kiện khi chọn 1 tab
     *
     * @return
     */
    private ChangeListener menuTabbed_Change() {
        return new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                try {
                    quanLyKhachHangTab.refresh(true);
                    quanLyMatHangTab.refresh(true);
                    quanLyChoThueTab.refresh(true);
                    quanLyNhanVienTab.refresh(true);
                    thongKeTabbed.refresh();
                }catch(Exception e1){
                    return;
                }

                TabKhachHang.revalidate();
                TabKhachHang.repaint();
            }
        };
    }
    
    
    
    
    /**
     * Creates new form Main
     */
    public Admin() throws Exception {
        initComponents();
        
         prepareUI();
         System.out.println("Hello world");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabKhachHang = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 1186, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabKhachHang;
    // End of variables declaration//GEN-END:variables
}
